site:
  title: RKE2 Documentation
  url: /
  start_page: main@rke2-product-docs:en:introduction.adoc

content:
  sources:
  - url: ./
    branches: [main]

#ui:
#  bundle:
#    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
#    snapshot: true
#  supplemental_files: ./susecom-2023

# Description: SUSE UI bundle which needs to be configured
ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./product-docs-supplemental-files

asciidoc:
  extensions:
    - '@asciidoctor/tabs'

antora:
  extensions:
    - require: '@sntke/antora-mermaid-extension' # <1>
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs # <2>
      script_stem: header-scripts # <3>
      mermaid_initialize_options: # <4>
        start_on_load: true